url: https://aigora.github.io/
baseurl:

# Site settings
title: AIGORA
email: raquel.cedazo@upm.es
description: "AIGORA: Aprendizaje de Informática con Github Organizado en Repositorios Abiertos"


# Team names, titles and social links
people:
- name: Raquel Cedazo León
  pic: 1
  position: Profesora UPM
  social:
    - title: twitter
      url: #

- name: Óscar Perpiñán Laguimeiro
  pic: 2
  position: Profesor UPM
  social:
    - title: twitter
      url: #

- name: Julia Uruel Sanz
  pic: 3
  position: Estudiante UPM
  social:
    - title: twitter
      url: #

- name: Miguel Pérez Mateo
  pic: 4
  position: Estudiante UPM
  social:
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UC650HXxycOj-tz2Z5cW-kFA
  - title: github
    url: http://github.com/aigora/

# Postal address (add as many lines as necessary)
address:
  - line: ETS de Ingeniería y Diseño Industrial
  - line: Ronda de Valencia, 3, Madrid 28012

# Build settings
markdown: kramdown
permalink: pretty
